[tool.pysen]
version = "0.9"

[tool.pysen.lint]
enable_black = true
enable_flake8 = true
enable_isort = true
enable_mypy = true

isort_known_first_party = ["deteval"]

[[tool.pysen.lint.mypy_targets]]
paths = ["deteval/", "tests/"]
